# Chicago Homelessness Data Source Inventory

## Purpose

This notebook creates a structured inventory of the datasets planned for the Chicago Housing Instability and Resource Allocation project.

The inventory records what each source measures, its time period, how it will be used, and its main limitations.

## Measurement Rule

These datasets do not all measure the same thing. PIT measures literal homelessness on one night. ACS and CHAS measure household and housing conditions. The CCH estimate uses a broader annual definition that includes doubled-up homelessness.

In [1]:
import sys

print("Python being used:", sys.executable)

Python being used: /workspaces/chicago-homelessness-resource-allocation/chicago-homelessness-resource-allocation/.venv-2/bin/python

In [2]:
from pathlib import Path

import pandas as pd

In [3]:
current_folder = Path.cwd()

if current_folder.name == "notebooks":
    project_root = current_folder.parent
else:
    project_root = current_folder

print("Current folder:", current_folder)
print("Project root:", project_root)

Current folder: /workspaces/chicago-homelessness-resource-allocation/chicago-homelessness-resource-allocation/notebooks
Project root: /workspaces/chicago-homelessness-resource-allocation/chicago-homelessness-resource-allocation

In [4]:
source_records = [
    {
        "source_name": "Chicago 2026 Point-in-Time Snapshot",
        "organization": "City of Chicago",
        "data_type": "Homelessness count",
        "coverage": "Chicago citywide",
        "latest_period": "January 22, 2026",
        "priority": "Primary",
        "planned_use": "Citywide sheltered and unsheltered trend context",
        "main_limitation": "One-night estimate that excludes doubled-up and other unstable housing",
        "access_url": "https://www.chicago.gov/city/en/depts/fss/provdrs/emerg/svcs/PITcount.html",
    },
    {
        "source_name": "HUD PIT and Housing Inventory Count",
        "organization": "U.S. Department of Housing and Urban Development",
        "data_type": "Homelessness and system inventory",
        "coverage": "Chicago Continuum of Care IL-510",
        "latest_period": "January 2025",
        "priority": "Primary",
        "planned_use": "Historical PIT trends and system-level housing inventory",
        "main_limitation": "Inventory is not the same as live vacancies or neighborhood access",
        "access_url": "https://www.huduser.gov/portal/datasets/ahar/2025-ahar-part-1-pit-estimates-of-homelessness-in-the-us.html",
    },
    {
        "source_name": "2020-2024 ACS Five-Year Estimates",
        "organization": "U.S. Census Bureau",
        "data_type": "Housing and demographic estimates",
        "coverage": "Census tracts and selected block groups",
        "latest_period": "2020-2024",
        "priority": "Primary",
        "planned_use": "Rent burden, income, poverty, tenure, and vacancy indicators",
        "main_limitation": "Pooled five-year estimates with margins of error; not homelessness counts",
        "access_url": "https://www.census.gov/data/developers/data-sets/acs-5year.html",
    },
    {
        "source_name": "HUD Comprehensive Housing Affordability Strategy",
        "organization": "U.S. Department of Housing and Urban Development",
        "data_type": "Housing need estimates",
        "coverage": "Multiple geographic levels",
        "latest_period": "2018-2022",
        "priority": "Primary",
        "planned_use": "Housing problems and cost burden among low-income households",
        "main_limitation": "Older period than the ACS data and some estimates are suppressed",
        "access_url": "https://www.huduser.gov/portal/datasets/cp.html",
    },
    {
        "source_name": "Affordable Rental Housing Developments",
        "organization": "City of Chicago",
        "data_type": "Affordable housing locations and units",
        "coverage": "Chicago properties",
        "latest_period": "Updated December 30, 2024",
        "priority": "Primary",
        "planned_use": "Measure documented city-supported affordable housing supply",
        "main_limitation": "Incomplete inventory with no real-time availability or current rent information",
        "access_url": "https://data.cityofchicago.org/d/s6ha-ppgi",
    },
    {
        "source_name": "Chicago Community Area Boundaries",
        "organization": "City of Chicago",
        "data_type": "Geographic boundaries",
        "coverage": "77 Chicago community areas",
        "latest_period": "Geometry updated April 22, 2025",
        "priority": "Primary",
        "planned_use": "Spatial joins and community-area maps",
        "main_limitation": "Administrative boundaries can hide differences within a community area",
        "access_url": "https://data.cityofchicago.org/d/igwz-8jzy",
    },
    {
        "source_name": "CCH Homeless Estimate",
        "organization": "Chicago Coalition to End Homelessness",
        "data_type": "Broader annual homelessness estimate",
        "coverage": "Chicago citywide",
        "latest_period": "Calendar year 2024",
        "priority": "Supplementary",
        "planned_use": "Explain how homelessness estimates change under broader definitions",
        "main_limitation": "Modeled annual estimate that is not directly comparable to the one-night PIT count",
        "access_url": "https://chicagohomeless.org/homelessestimate/",
    },
]

In [5]:
sources = pd.DataFrame(source_records)

print("Number of sources:", len(sources))
display(sources)

Number of sources: 7

,source_name,organization,data_type,coverage,latest_period,priority,planned_use,main_limitation,access_url
0,Chicago 2026 Point-in-Time Snapshot,City of Chicago,Homelessness count,Chicago citywide,"January 22, 2026",Primary,Citywide sheltered and unsheltered trend context,One-night estimate that excludes doubled-up an...,https://www.chicago.gov/city/en/depts/fss/prov...
1,HUD PIT and Housing Inventory Count,U.S. Department of Housing and Urban Development,Homelessness and system inventory,Chicago Continuum of Care IL-510,January 2025,Primary,Historical PIT trends and system-level housing...,Inventory is not the same as live vacancies or...,https://www.huduser.gov/portal/datasets/ahar/2...
2,2020-2024 ACS Five-Year Estimates,U.S. Census Bureau,Housing and demographic estimates,Census tracts and selected block groups,2020-2024,Primary,"Rent burden, income, poverty, tenure, and vaca...",Pooled five-year estimates with margins of err...,https://www.census.gov/data/developers/data-se...
3,HUD Comprehensive Housing Affordability Strategy,U.S. Department of Housing and Urban Development,Housing need estimates,Multiple geographic levels,2018-2022,Primary,Housing problems and cost burden among low-inc...,Older period than the ACS data and some estima...,https://www.huduser.gov/portal/datasets/cp.html
4,Affordable Rental Housing Developments,City of Chicago,Affordable housing locations and units,Chicago properties,"Updated December 30, 2024",Primary,Measure documented city-supported affordable h...,Incomplete inventory with no real-time availab...,https://data.cityofchicago.org/d/s6ha-ppgi
5,Chicago Community Area Boundaries,City of Chicago,Geographic boundaries,77 Chicago community areas,"Geometry updated April 22, 2025",Primary,Spatial joins and community-area maps,Administrative boundaries can hide differences...,https://data.cityofchicago.org/d/igwz-8jzy
6,CCH Homeless Estimate,Chicago Coalition to End Homelessness,Broader annual homelessness estimate,Chicago citywide,Calendar year 2024,Supplementary,Explain how homelessness estimates change unde...,Modeled annual estimate that is not directly c...,https://chicagohomeless.org/homelessestimate/

In [6]:
expected_columns = [
    "source_name",
    "organization",
    "data_type",
    "coverage",
    "latest_period",
    "priority",
    "planned_use",
    "main_limitation",
    "access_url",
]
assert len(sources) == 7, "The inventory should contain seven sources."
assert list(sources.columns) == expected_columns, "The columns are incorrect or out of order."
assert sources["source_name"].is_unique, "The source_name column should have unique values."
assert not sources["access_url"].isnull().any(), "The access_url column should not contain null values."
assert sources["access_url"].str.startswith("https://").all(), "At least one URL is not secure."
print("All inventory validation checks passed.")

All inventory validation checks passed.

In [7]:
print("Missing values by column:")
display(sources.isna().sum())

print("Duplicate source names:", sources["source_name"].duplicated().sum())
print("All links use HTTPS:", sources["access_url"].str.startswith("https://").all())

Missing values by column:

source_name        0
organization       0
data_type          0
coverage           0
latest_period      0
priority           0
planned_use        0
main_limitation    0
access_url         0
dtype: int64

Duplicate source names: 0
All links use HTTPS: True

In [8]:
output_path = project_root / "data" / "processed" / "data_source_inventory.csv"

output_path.parent.mkdir(parents=True, exist_ok=True)
sources.to_csv(output_path, index=False)

print("Saved inventory to:", output_path)

Saved inventory to: /workspaces/chicago-homelessness-resource-allocation/chicago-homelessness-resource-allocation/data/processed/data_source_inventory.csv

In [9]:
saved_sources = pd.read_csv(output_path)


print("Saved CSV dimensions :", saved_sources.shape)
display(saved_sources)

Saved CSV dimensions : (7, 9)

,source_name,organization,data_type,coverage,latest_period,priority,planned_use,main_limitation,access_url
0,Chicago 2026 Point-in-Time Snapshot,City of Chicago,Homelessness count,Chicago citywide,"January 22, 2026",Primary,Citywide sheltered and unsheltered trend context,One-night estimate that excludes doubled-up an...,https://www.chicago.gov/city/en/depts/fss/prov...
1,HUD PIT and Housing Inventory Count,U.S. Department of Housing and Urban Development,Homelessness and system inventory,Chicago Continuum of Care IL-510,January 2025,Primary,Historical PIT trends and system-level housing...,Inventory is not the same as live vacancies or...,https://www.huduser.gov/portal/datasets/ahar/2...
2,2020-2024 ACS Five-Year Estimates,U.S. Census Bureau,Housing and demographic estimates,Census tracts and selected block groups,2020-2024,Primary,"Rent burden, income, poverty, tenure, and vaca...",Pooled five-year estimates with margins of err...,https://www.census.gov/data/developers/data-se...
3,HUD Comprehensive Housing Affordability Strategy,U.S. Department of Housing and Urban Development,Housing need estimates,Multiple geographic levels,2018-2022,Primary,Housing problems and cost burden among low-inc...,Older period than the ACS data and some estima...,https://www.huduser.gov/portal/datasets/cp.html
4,Affordable Rental Housing Developments,City of Chicago,Affordable housing locations and units,Chicago properties,"Updated December 30, 2024",Primary,Measure documented city-supported affordable h...,Incomplete inventory with no real-time availab...,https://data.cityofchicago.org/d/s6ha-ppgi
5,Chicago Community Area Boundaries,City of Chicago,Geographic boundaries,77 Chicago community areas,"Geometry updated April 22, 2025",Primary,Spatial joins and community-area maps,Administrative boundaries can hide differences...,https://data.cityofchicago.org/d/igwz-8jzy
6,CCH Homeless Estimate,Chicago Coalition to End Homelessness,Broader annual homelessness estimate,Chicago citywide,Calendar year 2024,Supplementary,Explain how homelessness estimates change unde...,Modeled annual estimate that is not directly c...,https://chicagohomeless.org/homelessestimate/